sudo: false

language: python

env:
  global:
    # Doctr deploy key for pydata/pandas-datareader
    - secure: "iGbOAbBSV5y0TKDh2CifRSk6OpLA9GbEEL/hscHFLSDDUCWcdfvYXda3SWJFWyoQ5QUxSigXWd+ukr4u92d7lmB7m3TWj6BAMNuRpatTgnejLNwLvNeYdvLAxPvx39Cq85frd1Rx1beBLn3h/4wm4Ah+dR5W9NH8+x3OuZMH3Eo="


matrix:
  fast_finish: true
  include:
  - dist: trusty
    env:
      - PYTHON=2.7 PANDAS=0.19.2
  - dist: trusty
    env:
      - PYTHON=2.7 PANDAS=0.22
  - dist: trusty
    env:
      - PYTHON=3.5 PANDAS=0.19.2
  - dist: trusty
    env:
      - PYTHON=3.5 PANDAS=0.20.3
  - dist: trusty
    env:
      - PYTHON=3.6 PANDAS=0.21.1
  - dist: trusty
    env:
      - PYTHON=3.6 PANDAS=0.22 DOCBUILD=true
  # In allow failures
  - dist: trusty
    env:
      - PYTHON=3.6 PANDAS="MASTER"
  allow_failures:
    - dist: trusty
      env:
        - PYTHON=3.6 PANDAS="MASTER"

install:
  - pip install -qq flake8
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.  We do this
  # conditionally because it saves us some downloading if the version is
  # the same.
  - if [[ "$PYTHON" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels pandas
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON coverage setuptools html5lib lxml pytest pytest-cov wrapt
  - source activate test-environment
  - if [[ "$PANDAS" == "MASTER" ]]; then
      conda install numpy pytz python-dateutil;
      PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com";
      pip install --pre --upgrade --timeout=60 -f $PRE_WHEELS pandas;
    else
      conda install pandas=$PANDAS;
    fi
  - if [[ $DOCBUILD ]]; then
      conda install sphinx ipython matplotlib;
      pip install sphinx_rtd_theme doctr;
    fi
  - pip install beautifulsoup4
  - pip install coveralls --quiet
  - conda list
  - python setup.py install

script:
    - export ENIGMA_API_KEY=$ENIGMA_API_KEY
    - pytest -s -r xX --cov-config .coveragerc --cov=pandas_datareader --cov-report xml:/tmp/cov-datareader.xml --junitxml=/tmp/datareader.xml
    - flake8 --version
    - flake8 pandas_datareader

after_success:
  - |
    if [[ ${DOCBUILD} ]]; then
      cd docs
      make html && make html
      cd ..
      doctr deploy devel --build-tags
      if [[ -z ${TRAVIS_TAG} ]]; then
        echo "Not a tagged build."
      else
        doctr deploy stable --build-tags
      fi
    fi
  - coveralls
